potions:
  shrink:
    title: 'Крошик'
    scale: 0.5
    color: '#bfff00'
    duration: 60
    description: "Уменьшает в 2 раза"
  normal:
    title: 'Нормализатор'
    scale: 1.0
    color: '#00ffff'
    duration: 60
    description: "Нормализует ваш размер"
  giant:
    title: 'Гигантизм'
    scale: 2.0
    color: '#ff0000'
    duration: 60
    description: "Увеличивает размер в 2 раза"