potions: #Список зелий
  shrink: #Название зелья
    title: 'Крошик' #То что будет видно игрокам, название с учетом языка сервера
    attributes: #Список атрибутов, атрибуты можно посмотреть тут 'https://minecraft.wiki/w/Attribute'
      "minecraft:scale": 0.5 #Атрибут, который меняет размер игрока, по умолчанию 1
      "minecraft:step_height": 0.2 #Атрибут высоты авто подъема на блоки, по умолчанию 0.7
      "minecraft:movement_speed": 0.1 # Атрибут скорости игрока, делает быстрее на 0.1
    color: '#bfff00' #Цвет бутылочки зелья и его отображения в чате
    duration: 40 #Длительность зелья, в секундах
    description: "Уменьшает в 2 раза, это плохо?" #Описание зелья
    particleType: "firework" #Патриклы при использовании, список патриклов можно посмотреть тут 'https://minecraft.wiki/w/Particles_(Java_Edition)'
  normal:
    title: 'Гравитрон'
    attributes:
      "minecraft:gravity": 0.02
      "minecraft:safe_fall_distance": 6
    color: '#00ffff'
    duration: 120
    description: "Гравитация теперь добрее к вам"
    particleType: "white_smoke"
  giant:
    title: 'Гигантизм'
    attributes:
      "minecraft:scale": 1.5
      "minecraft:step_height": 1.6
      "minecraft:movement_speed": 0.07
    color: '#ff0000'
    duration: 50
    description: "Увеличивает размер в 2 раза, вам тяжело двигаться?"
    particleType: "composter"
  abyss:
    title: 'Пучина'
    attributes:
      "minecraft:oxygen_bonus": 5
      "minecraft:submerged_mining_speed": 1.5
      "minecraft:water_movement_efficiency": 0.9
      "minecraft:step_height": 0.1
      "minecraft:safe_fall_distance": 1
    color: '#26fe1b'
    duration: 80
    description: "В воде вам становится гораздо лучше"
    particleType: "sculk_charge_pop"