potions:
  shrink:
    title: 'Крошик'
    attributes:
      "minecraft:scale": 0.5
      "minecraft:step_height": 2
    color: '#bfff00'
    duration: 20
    description: "Уменьшает в 2 раза"
    particleType: "firework"
  normal:
    title: 'Нормализатор'
    attributes:
      "minecraft:scale": 0.5
      "minecraft:step_height": 2
    color: '#00ffff'
    duration: 200
    description: "Нормализует ваш размер"
    particleType: "cherry_leaves"
  giant:
    title: 'Гигантизм'
    attributes:
      "minecraft:scale": 0.5
      "minecraft:step_height": 2
    color: '#ff0000'
    duration: 50
    description: "Увеличивает размер в 2 раза"
    particleType: "composter"