name: ChangeMyHeight
version: ${version}
main: ru.edenor.changeMyHeight.ChangeMyHeight
api-version: '1.21.7'
author: Totilak
contributors: [WesOrangePower]
description: desc
folia-supported: true
permissions:
  cmh.give:
    description: Права для выдачи зелий
  cmh.use:
    description: Права для использований плагина, как игрок (cmh check)
  cmh.list:
    description: Права для просмотра списка зелий
